workflow:
    - second_job_name
shared:
    image: node:6


jobs:
    main:
        steps:
            - hello: echo hi world
            - set: meta set coverage 99.52
            - get: meta get coverage
    second_job_name:
        steps:
            - fetch: meta get coverage
            - reaching: meta get
