---
shared:
    image: slikshooz/timeouttest:latest


jobs:
    main:
        requires: [ ~commit, ~pr ]
        annotations:
            beta.screwdriver.cd/timeout: 45
        steps:
            - hello: echo hi world; echo $SD_BUILD_TIMEOUT
            - tired: sleep 120
            - fail: echo YOU SHOULD NOT BE HERE; exit 2
