workflow:
    - deploy
shared:
    image: node:6


jobs:
    main:
        steps:
            - hello: echo hi world
            - set_coverage: /opt/sd/meta set coverage 99.52
            - get_coverage: /opt/sd/meta get coverage
    deploy:
        steps:
            - check_coverage: /opt/sd/meta get coverage
            - deploy_to_production: echo secret script here
