---
shared:
  image: slikshooz/timeouttest:latest

jobs:
  main:
    annotations:
      beta.screwdriver.cd/cpu: MICRO
      beta.screwdriver.cd/ram: MICRO
    requires: [~commit]
    steps:
    - hello: echo hi world; echo $SD_BUILD_TIMEOUT
    - teardown-1: env
  npm:
    annotations:
      beta.screwdriver.cd/cpu: MICRO
      beta.screwdriver.cd/ram: MICRO
    image: node:8
    requires: [~pr]
    steps:
    - install: npm install
