workflow:
    - second_job_name
shared:
    image: node:6


jobs:
    main:
        steps:
            - hello: echo hi world
            - set: /opt/sd/meta set coverage 99.52
            - get: /opt/sd/meta get coverage
    second_job_name:
        steps:
            - fetch: /opt/sd/meta get coverage
            - reaching: /opt/sd/meta get
