---
shared:
    image: slikshooz/timeouttest:latest


jobs:
    main:
        annotations:
            beta.screwdriver.cd/timeout: 1
        steps:
            - hello: echo hi world; echo $SD_BUILD_TIMEOUT
            - tired: sleep 180
            - fail: echo YOU SHOULD NOT BE HERE; exit 2
