---
shared:
    image: slikshooz/timeouttest:latest


jobs:
    main:
        requires: [ ~commit, ~pr ]
        steps:
            - hello: echo hi world; echo $SD_BUILD_TIMEOUT
            - tired: sleep 6000
            - fail: echo YOU SHOULD NOT BE HERE; exit 2
