---
shared:
    image: screwdrivercd/launcher:latest


jobs:
    main:
        description: Darren is awesome
        steps:
            - hello: echo hi world
            - maybe: which asdfzxcvasdfqwer1234
