workflow:
    - second_job_name
shared:
    image: node:6


jobs:
    main:
        steps:
            - hello: echo hi world
    second_job_name:
        steps:
            - myname: echo second_job
