---
shared:
  image: slikshooz/timeouttest:latest

jobs:
  main:
    annotations:
      beta.screwdriver.cd/cpu: MICRO
      beta.screwdriver.cd/ram: MICRO
    requires: [~pr, ~commit]
    steps:
    - hello: echo hi world; echo $SD_BUILD_TIMEOUT
    - tired: sleep 180
    - fail: echo YOU SHOULD NOT BE HERE; exit 2
