---
shared:
    image: slikshooz/timeouttest:latest


jobs:
    main:
        steps:
            - hello: echo hi world
            - tired: sleep 180
            - fail: echo YOU SHOULD NOT BE HERE; exit 2
